server:
  port: 9001
  
  #spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_microservices?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=microservices
#spring.datasource.password=microservices
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:    base-url: http://localhost:9411  


#spring:
#  datasource:
#   url: jdbc:mysql://localhost:3306/demodatabase 
#    username: microservices
#    password: microservices
 
 
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect   
        
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#             defalultZone: http://localhost:8761/eureka
#  instance:
#         hostname: localhost           
     
        
    
    
    